FROM --platform=linux/amd64 node:20.11.1-alpine

# add chromium pakage for puppeteer
RUN apk add --no-cache chromium

RUN node -v

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4500

CMD [ "npm", "run", "start:production"]