import express from "express";
import welcome from "./welcome.js";
import AuthAPIs from "./auth.js";
import UserAPIs from "./user.js";
import TransactionAPIs from "./transactions.js";
import Payment from "./directa.js";
import Payees from "./payees.js";
import Contacts from "./contacts.js";
import ExchangeRate from "./exchangeRates.js";
import Notification from "./notifications.js";
import Admin from "./admin.js";
import Users from "../models/users.js";
import authMiddleware from "../middlewares/authMiddleware.js";
import verificationMiddleware from "../middlewares/verificationMiddleware.js";
import States from "./states.js";
import Card from "./card.js";
import ApplePay from "./applePay.js";
import Hupspot from "./hubspot.js";
import FinixAPIs from "./finix.js";
import AppApis from "./appVersion.js";
import checkFeatureStatus from "../middlewares/checkFeatureStatus.js";
import { FeatureNames } from "../constants/index.js";
import BusinessAPIs from "./stableBusiness.js";
import signatureValidationMiddleware from "../middlewares/validateStableBusinessApis.js";
import PromotionsAPIs from "./promotions.js";
import chat from "./chat.js";
import BanksAPIs from "./banks.js";
import CashoutBeneficiaryAPIs from "./cashoutBeneficiary.js";
import PaymentLinks from "./paymentLinks.js";
import QuickPay from "./quickPay.js";
import hmacMiddleware from "../middlewares/hmacDecryption.js";
import CommunityAPIs from "./communities.js";
import OnepayAPIs from "./onePay.js";
import KushkiAPIs from "./kushki.js";
import OnepayKushkiAPIs from "./onepayKushki.js";

const router = express.Router();

router.use("/welcome", hmacMiddleware(), welcome);
router.use("/auth", hmacMiddleware(), AuthAPIs);
router.use("/user", hmacMiddleware(), UserAPIs);
router.use("/transfer", hmacMiddleware(), authMiddleware(Users), verificationMiddleware, TransactionAPIs);
router.use("/payment", hmacMiddleware(), authMiddleware(Users), verificationMiddleware, Payment);
router.use("/onepay", authMiddleware(Users), OnepayAPIs);
router.use("/onepay-kushki", hmacMiddleware(), authMiddleware(Users), OnepayKushkiAPIs);
router.use("/kushki", hmacMiddleware(), authMiddleware(Users), KushkiAPIs);
router.use("/cashout/beneficiary", hmacMiddleware(), authMiddleware(Users), verificationMiddleware, CashoutBeneficiaryAPIs);
router.use("/payees", hmacMiddleware(), authMiddleware(Users), Payees);
router.use("/contacts", hmacMiddleware(), authMiddleware(Users), verificationMiddleware, Contacts);
router.use("/exchange", hmacMiddleware(), authMiddleware(Users), verificationMiddleware, ExchangeRate);
router.use("/notifications", hmacMiddleware(), authMiddleware(Users), Notification);
router.use("/states", hmacMiddleware(), authMiddleware(Users), verificationMiddleware, States);
router.use("/card", hmacMiddleware(), authMiddleware(Users), verificationMiddleware, Card);
router.use("/applepay", hmacMiddleware(), authMiddleware(Users), ApplePay);
router.use("/hubspot", hmacMiddleware(), authMiddleware(Users), Hupspot);
router.use("/promotions", hmacMiddleware(), authMiddleware(Users), PromotionsAPIs);
router.use("/finix", hmacMiddleware(), authMiddleware(Users), checkFeatureStatus(FeatureNames.finix), FinixAPIs);
router.use("/app", AppApis);
router.use("/business", signatureValidationMiddleware, BusinessAPIs);
router.use("/admin", Admin);
router.use("/chat", chat);
router.use("/banks", hmacMiddleware(), authMiddleware(Users), BanksAPIs);
router.use("/payment_links", PaymentLinks);
router.use("/quick-payment", hmacMiddleware(), QuickPay);
router.use("/communities", hmacMiddleware(), authMiddleware(Users), CommunityAPIs);

export default router;
